timeout: 5

/YamKernel
    protocol: limine
    kernel_path: boot():/boot/yamkernel.elf
    module_path: boot():/boot/wallpaper.bin
    module_path: boot():/boot/logo.bin
    module_path: boot():/boot/authd.elf
    module_path: boot():/boot/hello.elf
    module_path: boot():/boot/exec-test.elf
    module_path: boot():/boot/orphan-test.elf
